### ISSUE TITLE
Error: "input": conflicts with input_path

### ISSUE THREAD

**Issue by wweaver** [jnonino/terraform-aws-ecs-fargate-scheduled-task#1]
It seems that the `aws_cloudwatch_event_target.ecs_scheduled_task` provides both `input` and `input_path` which according to terraform 0.12 considers that invalid as only one of those options can be specified.

Getting this when trying to run plan.

```
Error: "input": conflicts with input_path

  on .terraform/modules/.../jnonino-terraform-aws-ecs-fargate-scheduled-task-0fbb11c/main.tf line 48, in resource "aws_cloudwatch_event_target" "ecs_scheduled_task":
  48: resource "aws_cloudwatch_event_target" "ecs_scheduled_task" {
```

**Comment by jnonino** [comment]
Hi, thanks for the feedback. Try the new version 1.0.3 (https://registry.terraform.io/modules/jnonino/ecs-fargate-scheduled-task/aws/1.0.3) and let me know if I can close this issue

**Comment by wweaver** [comment]
Yes that particular bug is fixed. Thanks for the extremely quick response. Still playing around with the code to see if it works for my needs. My first time creating scheduled ECS tasks.
